import { Navbar } from '@/components/common/Navbar';
import { Footer } from '@/components/common/Footer';

export const metadata = { title: 'Terms & Conditions' };

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main id="main-content" className="container-page max-w-4xl py-16">
        <h1 className="font-display text-display-md text-ink-900">Terms &amp; Conditions</h1>
        <p className="mt-2 text-sm text-ink-400">Last updated: July 2026</p>

        <div className="mt-8 space-y-6 text-ink-600">
          <section>
            <h2 className="font-display text-lg text-ink-900">What this service is</h2>
            <p className="mt-2">
              FlightOptimizer is a portfolio project demonstrating a flight-search optimization engine — nearby
              airport expansion, flexible date search, and multi-city route scoring. It is{' '}
              <strong>not a licensed travel agency or booking platform</strong>. You cannot purchase a ticket
              through this application.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ink-900">Flight data accuracy</h2>
            <p className="mt-2">
              By default, flight prices and schedules are generated by a mock provider that models realistic
              pricing based on distance — they are illustrative, not live fares. Where a real provider (Amadeus) is
              enabled, prices reflect that provider’s test/sandbox environment and should not be relied on for an
              actual purchase decision.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ink-900">Accounts</h2>
            <ul className="mt-2 list-disc space-y-1.5 pl-5">
              <li>You’re responsible for keeping your password confidential.</li>
              <li>You must provide a real, working email address to register.</li>
              <li>We may suspend accounts used for abuse, scraping, or attempts to bypass rate limits.</li>
            </ul>
          </section>

          <section>
            <h2 className="font-display text-lg text-ink-900">Paid plans</h2>
            <p className="mt-2">
              Pro and Business pricing tiers are displayed for demonstration purposes. As noted in our{' '}
              <a href="/privacy" className="text-horizon-700 underline underline-offset-2">
                Privacy Policy
              </a>
              , payment processing is not currently active — no charges can be made through this application at
              this time.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ink-900">No warranty</h2>
            <p className="mt-2">
              This application is provided “as is,” without warranty of any kind. Recommendations, prices, and
              routes are algorithmic outputs and may contain errors — always verify details independently before
              making real travel plans or purchases elsewhere.
            </p>
          </section>

          <section>
            <h2 className="font-display text-lg text-ink-900">Changes</h2>
            <p className="mt-2">
              As this project evolves, these terms may change. Material changes will be reflected by updating the
              “Last updated” date above.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </>
  );
}
